<a href="https://colab.research.google.com/github/akhil-gali/dataScience_practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

#Create one dimensional Array in Numpy

In [2]:
import numpy as np   #inporting numpy Library

In [3]:
my_list = [1,2,3]
n = np.array(my_list)
n

array([1, 2, 3])

In [4]:
type(my_list)   # type method gives the type of given variable

list

In [5]:
type(n)    # type method gives the type of given variable

numpy.ndarray

# Creating Multidimesional Array

In [6]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
md = np.array(my_list2)
md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(md)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
type(md)  # type method gives the type of given variable

numpy.ndarray

In [9]:
md.shape # Shape method is used to return the shape of the array..

(3, 3)

#Generating Evenly Spaced values within the Given Limit

In [10]:
np.arange(0,10)  # gives array of numbers (int type) start from "0" till "9" excluding the last digit

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(20)  #if start number doesn't mention, Np will generate starting from 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(0,20,3) #will generate numbers from "0" to "20" with interval of "3"

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
for i in range(1,11,2):
  print(i)                    #printing the Number

1
3
5
7
9


In [14]:
for i in np.arange(1,12,2):
  new_array = np.array(np.arange(i,12,2))
  print(new_array)        #Printing the Array

[ 1  3  5  7  9 11]
[ 3  5  7  9 11]
[ 5  7  9 11]
[ 7  9 11]
[ 9 11]
[11]


In [15]:
zero_array = np.zeros((5,6))     #for writing Zero array and shape we use double braces like((5,6)) in the example
print(zero_array)                #for 1 dimensional Array we can write like np.zeros(100) which will return 100 zeros 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
zero_array.reshape(6,5)             #for reshaping no need of Double braces

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zero_array                #the reshape function doesn't change the actual number of rows and columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
ones_array = np.ones((4,8))    #same as zeros
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
ones_array.reshape(8,4)   #same as zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones_array            #columns and rows doesn't change as zeros function

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
identity_array = np.eye(10)   #will give 
identity_array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
O= np.linspace(0,50,8) #Linspace function returns 3rd parameter(6) evenly spaced float Values start from 1st parameter to 2nd parameter
O                      # linspace includes first and last values.

array([ 0.        ,  7.14285714, 14.28571429, 21.42857143, 28.57142857,
       35.71428571, 42.85714286, 50.        ])

In [23]:
len(O)

8

In [24]:
O.resize(4,2) #resize function will Change the shape of original array..Unlike reshape Function
O

array([[ 0.        ,  7.14285714],
       [14.28571429, 21.42857143],
       [28.57142857, 35.71428571],
       [42.85714286, 50.        ]])

In [25]:
O

array([[ 0.        ,  7.14285714],
       [14.28571429, 21.42857143],
       [28.57142857, 35.71428571],
       [42.85714286, 50.        ]])

# Generating Random Values

In [26]:
rand_function =np.random.rand(5,5) #will generate random values in unifrom Distribution between [0,1] in given shape and generate new numbers for each time we run
rand_function 

array([[0.79875321, 0.33382608, 0.87735628, 0.13450103, 0.8771614 ],
       [0.4260056 , 0.18310279, 0.91175819, 0.79281785, 0.31715658],
       [0.77531989, 0.1927848 , 0.39013813, 0.26665369, 0.98226376],
       [0.54270251, 0.28646396, 0.96958607, 0.11017908, 0.54029679],
       [0.72134233, 0.01192978, 0.81383925, 0.11425186, 0.95534135]])

In [27]:
a=np.random.randn(5,3) # will generate random values in Standard normal distribution
a                      # it also generates new values every time we run

array([[-0.440152  , -0.20910341, -1.51199507],
       [ 0.13134221,  1.07922869,  0.84289985],
       [ 1.075296  ,  1.2523916 , -0.65719618],
       [ 1.03996287, -0.23000476,  2.06578906],
       [-0.83840579,  0.51722695, -0.81429548]])

In [28]:
#Generating 15 random numbers between 10 and 60
randint_function=np.random.randint(6,25,15)  #generate 15 random numbers with repetion allowed and including lower limit excluding Higher limit
randint_function

array([ 6, 11, 17, 21, 20,  9, 19,  8, 17, 16,  9, 12, 17,  6, 17])

In [29]:
randint_function.reshape(5,3)

array([[ 6, 11, 17],
       [21, 20,  9],
       [19,  8, 17],
       [16,  9, 12],
       [17,  6, 17]])

In [30]:
randint_function_1 = np.random.randint(6,25,(5,3))  # we can directly define the shape as 3rd parameter
randint_function_1

array([[14, 18, 22],
       [23,  7,  6],
       [13, 18, 18],
       [16, 19, 12],
       [15, 20, 16]])

# Indexing and Slicing

In [31]:
p = np.random.randint(0,15,8)
p

array([ 8, 10,  3, 10, 11,  8,  6,  9])

In [32]:
p[0] #will return value at zero index

8

In [33]:
p[-3] # will return the value which is in third place from Last. negative indexing starts from -1,-2,-3,-4....

8

In [34]:
p[2:8] #will return set of values start from 2 index till 8 and doesnot include 8 index value

array([ 3, 10, 11,  8,  6,  9])

In [35]:
p[1:-4] #slicing includes negative indexing and does not include value of last index va;ue

array([10,  3, 10])

In [36]:
p[3:] #will return the array start from 3 rd index till last and includes last index value

array([10, 11,  8,  6,  9])

In [37]:
p[:-1] # will return the array start from 0 index till -1 index excluding -1 index value

array([ 8, 10,  3, 10, 11,  8,  6])

In [38]:
p[:] # will return the array fro 0 index till last index including last index value

array([ 8, 10,  3, 10, 11,  8,  6,  9])

In [39]:
var1 = np.random.randint(2,65,(5,5)) # return random integers betweeb 2(including) and 65(excluding) in (5,5) shape
var1

array([[16, 64, 48, 34,  7],
       [37,  2, 60, 52, 11],
       [55, 52, 11, 61, 26],
       [21, 43, 14, 44, 45],
       [48, 32, 61, 16, 18]])

In [40]:
var1[2] #will return array at index 2

array([55, 52, 11, 61, 26])

In [41]:
var1[2,2] #will return value at index 2 in row and 2 in column

11

In [42]:
var1[3,[0,-1,2]] #will return array which are of 3rd indexing row  0 index value and last index value and 2 index value

array([21, 45, 14])

                Use ":" symbol for selecting range


In [43]:
var1[3, 0:-2] #will slice the 3 rd indexed array and return array with values start from 0 index till-2 index and doesnot include -2 index value

array([21, 43, 14])

In [44]:
var1[3, 0:3]  #will slice the 3 rd indexed array and return array with values start from 0 index till3 index and doesnot include 3 index value

array([21, 43, 14])

In [45]:
var1[2:]      #return all the rows from 2 till last 

array([[55, 52, 11, 61, 26],
       [21, 43, 14, 44, 45],
       [48, 32, 61, 16, 18]])

In [46]:
var1[1:,2:]     #return all the rows from 1 till last and 2 nd column till last

array([[60, 52, 11],
       [11, 61, 26],
       [14, 44, 45],
       [61, 16, 18]])

#conditional Indexing

In [47]:
mn = np.random.randint(0,50,50)
mn

array([37, 24,  8,  4, 21,  1, 25,  8, 10, 44, 46, 36, 41,  8,  2, 31, 36,
       35, 32,  1, 37, 42, 31, 31, 24, 18, 46, 10,  6, 22, 17, 27, 34, 11,
       46, 38, 21, 49, 41, 47, 29,  4, 19, 18, 15,  0, 49, 34, 31, 38])

In [48]:
mn>25 # will return bollean according to condition

array([ True, False, False, False, False, False, False, False, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
       False, False, False, False,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True, False, False, False, False,
       False,  True,  True,  True,  True])

In [49]:
mn[mn>25]   #will return the values of mn which are obeying the condition

array([37, 44, 46, 36, 41, 31, 36, 35, 32, 37, 42, 31, 31, 46, 27, 34, 46,
       38, 49, 41, 47, 29, 49, 34, 31, 38])

In [50]:
mn[mn>30] = 25  #casting the value "25" to the values which are greater than 30
mn

array([25, 24,  8,  4, 21,  1, 25,  8, 10, 25, 25, 25, 25,  8,  2, 25, 25,
       25, 25,  1, 25, 25, 25, 25, 24, 18, 25, 10,  6, 22, 17, 27, 25, 11,
       25, 25, 21, 25, 25, 25, 29,  4, 19, 18, 15,  0, 25, 25, 25, 25])

In [51]:
mn.resize(10,5)
mn

array([[25, 24,  8,  4, 21],
       [ 1, 25,  8, 10, 25],
       [25, 25, 25,  8,  2],
       [25, 25, 25, 25,  1],
       [25, 25, 25, 25, 24],
       [18, 25, 10,  6, 22],
       [17, 27, 25, 11, 25],
       [25, 21, 25, 25, 25],
       [29,  4, 19, 18, 15],
       [ 0, 25, 25, 25, 25]])

#creating a copy

In [52]:
mn1 = mn[3:,2:]   #creating a copy according to indexes
mn1

array([[25, 25,  1],
       [25, 25, 24],
       [10,  6, 22],
       [25, 11, 25],
       [25, 25, 25],
       [19, 18, 15],
       [25, 25, 25]])

In [53]:
mn_copy = mn.copy()   #copy() will copy the mn values and store them intomn_copy

In [54]:
mn_copy

array([[25, 24,  8,  4, 21],
       [ 1, 25,  8, 10, 25],
       [25, 25, 25,  8,  2],
       [25, 25, 25, 25,  1],
       [25, 25, 25, 25, 24],
       [18, 25, 10,  6, 22],
       [17, 27, 25, 11, 25],
       [25, 21, 25, 25, 25],
       [29,  4, 19, 18, 15],
       [ 0, 25, 25, 25, 25]])

In [55]:
import pandas as pd   #importing Pandas Library

In [56]:
covid_stats = pd.read_csv("/content/covid_stats.csv") #read_csv function will read the csv file in given path

Cleaning the Data

In [57]:
covid_stats

State Wise Breakdown  Total Cases  Active Cases   nan    rec
0                   Maharashtra        20228         15649   779   3800
1                       Gujarat         7797          5234   472   2091
2                         Delhi         6542          4454    68   2020
3                    Tamil Nadu         6535          4667    44   1824
4                     Rajasthan         3708          1440   106   2162
5                Madhya Pradesh         3457          1766   211   1480
6                 Uttar Pradesh         3373          1800    74   1499
7                Andhra Pradesh         1930           999    44    887
8                 West Bengal**         1786          1243   171    372
9                        Punjab         1762          1574    31    157
10                    Telangana         1163           382    30    751
11            Jammu and Kashmir          836           459     9    368
12                    Karnataka          794           378    30    386
13                      Haryana          675           376     9    290
14                        Bihar          611           288     5    318
15                       Kerala          505            16     4    485
16                       Odisha          294           224     2     68
17                   Chandigarh          169           143     2     24
18                    Jharkhand          156           101     3     52
19                      Tripura          135           133     0      2
20                  Uttarakhand           67            20     1     46
21                        Assam           62            26     2     34
22                 Chhattisgarh           59            16     0     43
23            Himachal Pradesh‡           53            13     3     37
24                       Ladakh           42            25     0     17
25  Andaman and Nicobar Islands           33             0     0     33
26                    Meghalaya           13             2     1     10
27                  Puducherry†           10             3     0      7
28                          Goa            7             0     0      7
29                      Manipur            2             0     0      2
30      Dadra and Nagar Haveli*            1             1     0      0
31            Arunachal Pradesh            1             0     0      1
32                      Mizoram            1             0     0      1
33                     Nagaland            1             0     0      1
34                        Total        62808         41432  2101  19275

In [74]:
covid_stats_copy = covid_stats.copy()  #copying the csv file
covid_stats_copy = covid_stats_copy[:-1] #removed the total

In [75]:
covid_stats_copy.head()

State Wise Breakdown  Total Cases  Active Cases  nan   rec
0          Maharashtra        20228         15649  779  3800
1              Gujarat         7797          5234  472  2091
2                Delhi         6542          4454   68  2020
3           Tamil Nadu         6535          4667   44  1824
4            Rajasthan         3708          1440  106  2162

In [76]:
covid_stats_copy[['State','Dead','Recovered']] = covid_stats_copy[['State Wise Breakdown','nan','rec']] #copying  the columns and adding them to Dataframe

In [77]:
covid_stats_copy.head()

State Wise Breakdown  Total Cases  Active Cases  ...        State  Dead Recovered
0          Maharashtra        20228         15649  ...  Maharashtra   779      3800
1              Gujarat         7797          5234  ...      Gujarat   472      2091
2                Delhi         6542          4454  ...        Delhi    68      2020
3           Tamil Nadu         6535          4667  ...   Tamil Nadu    44      1824
4            Rajasthan         3708          1440  ...    Rajasthan   106      2162

[5 rows x 8 columns]

In [78]:
covid_stats_copy = covid_stats_copy.drop(['State Wise Breakdown','nan','rec'], axis=1) #Dropping the columns which are named improperly

In [79]:
covid_stats_copy.head()

Total Cases  Active Cases        State  Dead  Recovered
0        20228         15649  Maharashtra   779       3800
1         7797          5234      Gujarat   472       2091
2         6542          4454        Delhi    68       2020
3         6535          4667   Tamil Nadu    44       1824
4         3708          1440    Rajasthan   106       2162

In [90]:
covid_stats_copy['State'] # To return the values under State column

0                     Maharashtra
1                         Gujarat
2                           Delhi
3                      Tamil Nadu
4                       Rajasthan
5                  Madhya Pradesh
6                   Uttar Pradesh
7                  Andhra Pradesh
8                   West Bengal**
9                          Punjab
10                      Telangana
11              Jammu and Kashmir
12                      Karnataka
13                        Haryana
14                          Bihar
15                         Kerala
16                         Odisha
17                     Chandigarh
18                      Jharkhand
19                        Tripura
20                    Uttarakhand
21                          Assam
22                   Chhattisgarh
23              Himachal Pradesh‡
24                         Ladakh
25    Andaman and Nicobar Islands
26                      Meghalaya
27                    Puducherry†
28                            Goa
29            

In [80]:
#covid_stats_copy.re (['State','Total Cases','Active Cases','Dead','Recovered'], axis=1)

#Creating a Matrix

In [87]:
var_matrix = np.matrix([[1,3,6,10],[2,6,45,76,46],[1,52,85],[1.2,5,2]])  #syntax for creating Matrix
var_matrix

/usr/local/lib/python3.7/dist-packages/numpy/matrixlib/defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([1, 3, 6, 10]), list([2, 6, 45, 76, 46]),
         list([1, 52, 85]), list([1.2, 5, 2])]], dtype=object)

In [94]:
covid_stats_copy['Total Cases'].mean()   #will return the mean

1847.2941176470588

In [95]:
covid_stats_copy['Total Cases'].std()  #will return the Srandard Deviation

3855.2685205338025

In [96]:
covid_stats_copy['Total Cases'].var()    # Will retun the Varience

14863095.365418896

In [97]:
# to learn more on Numpy please visit : https://numpy.org/doc/stable/