<a href="https://colab.research.google.com/github/akhil-gali/dataScience_practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

#Create one dimensional Array in Numpy

In [ ]:
import numpy as np   #inporting numpy Library

In [ ]:
my_list = [1,2,3]
n = np.array(my_list)
n

array([1, 2, 3])

In [ ]:
type(my_list)   # type method gives the type of given variable

list

In [ ]:
type(n)    # type method gives the type of given variable

numpy.ndarray

# Creating Multidimesional Array

In [ ]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
md = np.array(my_list2)
md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(md)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(md)  # type method gives the type of given variable

numpy.ndarray

In [ ]:
md.shape # Shape method is used to return the shape of the array..

(3, 3)

#Generating Evenly Spaced values within the Given Limit

In [ ]:
np.arange(0,10)  # gives array of numbers (int type) start from "0" till "9" excluding the last digit

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(20)  #if start number doesn't mention, Np will generate starting from 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20,3) #will generate numbers from "0" to "20" with interval of "3"

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
for i in range(1,11,2):
  print(i)                    #printing the Number

1
3
5
7
9


In [ ]:
for i in np.arange(1,12,2):
  new_array = np.array(np.arange(i,12,2))
  print(new_array)        #Printing the Array

[ 1  3  5  7  9 11]
[ 3  5  7  9 11]
[ 5  7  9 11]
[ 7  9 11]
[ 9 11]
[11]


In [ ]:
zero_array = np.zeros((5,6))     #for writing Zero array and shape we use double braces like((5,6)) in the example
print(zero_array)                #for 1 dimensional Array we can write like np.zeros(100) which will return 100 zeros 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
zero_array.reshape(6,5)             #for reshaping no need of Double braces

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zero_array                #the reshape function doesn't change the actual number of rows and columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((4,8))    #same as zeros
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones_array.reshape(8,4)   #same as zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
ones_array            #columns and rows doesn't change as zeros function

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
identity_array = np.eye(10)   #will give 
identity_array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
O= np.linspace(0,50,8) #Linspace function returns 3rd parameter(6) evenly spaced float Values start from 1st parameter to 2nd parameter
O                      # linspace includes first and last values.

array([ 0.        ,  7.14285714, 14.28571429, 21.42857143, 28.57142857,
       35.71428571, 42.85714286, 50.        ])

In [ ]:
len(O)

8

In [ ]:
O.resize(4,2) #resize function will Change the shape of original array..Unlike reshape Function
O

array([[ 0.        ,  7.14285714],
       [14.28571429, 21.42857143],
       [28.57142857, 35.71428571],
       [42.85714286, 50.        ]])

In [ ]:
O

array([[ 0.        ,  7.14285714],
       [14.28571429, 21.42857143],
       [28.57142857, 35.71428571],
       [42.85714286, 50.        ]])

# Generating Random Values

In [ ]:
rand_function =np.random.rand(5,5) #will generate random values in unifrom Distribution between [0,1] in given shape and generate new numbers for each time we run
rand_function 

array([[0.8556216 , 0.31331236, 0.80485968, 0.08234614, 0.36872211],
       [0.89410209, 0.85960065, 0.85991465, 0.65659398, 0.01595787],
       [0.98886877, 0.97060632, 0.37090144, 0.65250669, 0.65713584],
       [0.04366382, 0.27287156, 0.54535772, 0.90096155, 0.96682051],
       [0.3922643 , 0.31275421, 0.98576439, 0.30606995, 0.65010961]])

In [ ]:
a=np.random.randn(5,3) # will generate random values in Standard normal distribution
a                      # it also generates new values every time we run

array([[ 0.24712523, -0.13480784,  0.14603167],
       [-0.67192813,  1.22960785, -0.89500062],
       [ 0.1713092 ,  0.51059885,  3.13798862],
       [ 0.84976747, -0.75654664,  1.3155237 ],
       [ 1.10388592,  0.40154017, -0.17770625]])

In [ ]:
#Generating 15 random numbers between 10 and 60
randint_function=np.random.randint(6,25,15)  #generate 15 random numbers with repetion allowed and including lower limit excluding Higher limit
randint_function

array([16, 13, 20, 20, 13, 14, 11,  7, 13, 11, 22, 19, 11, 22, 16])

In [ ]:
randint_function.reshape(5,3)

array([[16, 13, 20],
       [20, 13, 14],
       [11,  7, 13],
       [11, 22, 19],
       [11, 22, 16]])

In [ ]:
randint_function_1 = np.random.randint(6,25,(5,3))  # we can directly define the shape as 3rd parameter
randint_function_1

array([[17, 21, 19],
       [ 7, 24, 20],
       [22,  7, 15],
       [ 8, 21, 16],
       [12, 11,  8]])

# Indexing and Slicing

In [ ]:
p = np.random.randint(0,15,8)
p

array([ 9, 11,  9,  3,  7,  0,  9,  5])

In [ ]:
p[0] #will return value at zero index

9

In [ ]:
p[-3] # will return the value which is in third place from Last. negative indexing starts from -1,-2,-3,-4....

0

In [ ]:
p[2:8] #will return set of values start from 2 index till 8 and doesnot include 8 index value

array([9, 3, 7, 0, 9, 5])

In [ ]:
p[1:-4] #slicing includes negative indexing and does not include value of last index va;ue

array([11,  9,  3])

In [ ]:
p[3:] #will return the array start from 3 rd index till last and includes last index value

array([3, 7, 0, 9, 5])

In [ ]:
p[:-1] # will return the array start from 0 index till -1 index excluding -1 index value

array([ 9, 11,  9,  3,  7,  0,  9])

In [ ]:
p[:] # will return the array fro 0 index till last index including last index value

array([ 9, 11,  9,  3,  7,  0,  9,  5])

In [ ]:
var1 = np.random.randint(2,65,(5,5)) # return random integers betweeb 2(including) and 65(excluding) in (5,5) shape
var1

array([[47, 26, 18,  2, 56],
       [11, 42, 16,  4, 45],
       [42, 64, 58, 23, 22],
       [23, 11, 27,  8, 10],
       [51, 40, 38, 62, 56]])

In [ ]:
var1[2] #will return array at index 2

array([42, 64, 58, 23, 22])

In [ ]:
var1[2,2] #will return value at index 2 in row and 2 in column

58

In [ ]:
var1[3,[0,-1,2]] #will return array which are of 3rd indexing row  0 index value and last index value and 2 index value

array([23, 10, 27])

                Use ":" symbol for selecting range


In [ ]:
var1[3, 0:-2] #will slice the 3 rd indexed array and return array with values start from 0 index till-2 index and doesnot include -2 index value

array([23, 11, 27])

In [ ]:
var1[3, 0:3]  #will slice the 3 rd indexed array and return array with values start from 0 index till3 index and doesnot include 3 index value

array([23, 11, 27])

In [ ]:
var1[2:]      #return all the rows from 2 till last 

array([[42, 64, 58, 23, 22],
       [23, 11, 27,  8, 10],
       [51, 40, 38, 62, 56]])

In [ ]:
var1[1:,2:]     #return all the rows from 1 till last and 2 nd column till last

array([[16,  4, 45],
       [58, 23, 22],
       [27,  8, 10],
       [38, 62, 56]])