<a href="https://colab.research.google.com/github/akhil-gali/dataScience_practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

#Create one dimensional Array in Numpy

In [ ]:
import numpy as np   #inporting numpy Library

In [ ]:
my_list = [1,2,3]
n = np.array(my_list)
n

array([1, 2, 3])

In [ ]:
type(my_list)   # type method gives the type of given variable

list

In [ ]:
type(n)    # type method gives the type of given variable

numpy.ndarray

# Creating Multidimesional Array

In [ ]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
md = np.array(my_list2)
md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(md)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(md)  # type method gives the type of given variable

numpy.ndarray

In [ ]:
md.shape # Shape method is used to return the shape of the array..

(3, 3)

#Generating Evenly Spaced values within the Given Limit

In [ ]:
np.arange(0,10)  # gives array of numbers (int type) start from "0" till "9" excluding the last digit

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(20)  #if start number doesn't mention, Np will generate starting from 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20,3) #will generate numbers from "0" to "20" with interval of "3"

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
for i in range(1,11,2):
  print(i)                    #printing the Number

1
3
5
7
9


In [ ]:
for i in np.arange(1,12,2):
  new_array = np.array(np.arange(i,12,2))
  print(new_array)        #Printing the Array

[ 1  3  5  7  9 11]
[ 3  5  7  9 11]
[ 5  7  9 11]
[ 7  9 11]
[ 9 11]
[11]


In [ ]:
zero_array = np.zeros((5,6))     #for writing Zero array and shape we use double braces like((5,6)) in the example
print(zero_array)                #for 1 dimensional Array we can write like np.zeros(100) which will return 100 zeros 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
zero_array.reshape(6,5)             #for reshaping no need of Double braces

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zero_array                #the reshape function doesn't change the actual number of rows and columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((4,8))    #same as zeros
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones_array.reshape(8,4)   #same as zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
ones_array            #columns and rows doesn't change as zeros function

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
identity_array = np.eye(10)   #will give 
identity_array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
O= np.linspace(0,50,8) #Linspace function returns 3rd parameter(6) evenly spaced float Values start from 1st parameter to 2nd parameter
O                      # linspace includes first and last values.

array([ 0.        ,  7.14285714, 14.28571429, 21.42857143, 28.57142857,
       35.71428571, 42.85714286, 50.        ])

In [ ]:
len(O)

8

In [ ]:
O.resize(4,2) #resize function will Change the shape of original array..Unlike reshape Function
O

array([[ 0.        ,  7.14285714],
       [14.28571429, 21.42857143],
       [28.57142857, 35.71428571],
       [42.85714286, 50.        ]])

In [ ]:
O

array([[ 0.        ,  7.14285714],
       [14.28571429, 21.42857143],
       [28.57142857, 35.71428571],
       [42.85714286, 50.        ]])

# Generating Random Values

In [ ]:
rand_function =np.random.rand(5,5) #will generate random values in unifrom Distribution between [0,1] in given shape and generate new numbers for each time we run
rand_function 

array([[0.19232362, 0.15434386, 0.14760912, 0.64146537, 0.06909601],
       [0.32809184, 0.32985299, 0.03637272, 0.16369047, 0.65111883],
       [0.73154195, 0.83078869, 0.2526735 , 0.78448684, 0.80370063],
       [0.85771504, 0.25797734, 0.30560836, 0.09274839, 0.39392271],
       [0.94842324, 0.89256233, 0.89621693, 0.32252065, 0.05674566]])

In [ ]:
a=np.random.randn(5,3) # will generate random values in Standard normal distribution
a                      # it also generates new values every time we run

array([[ 0.58564096,  0.92855289, -0.64121882],
       [ 0.60932065,  0.92403712, -0.98567556],
       [ 2.68035783, -0.37648399,  1.25964287],
       [ 0.7062479 ,  0.49935829,  1.50810454],
       [-1.74626512, -0.2968618 ,  1.68927498]])

In [ ]:
#Generating 15 random numbers between 10 and 60
randint_function=np.random.randint(6,25,15)  #generate 15 random numbers with repetion allowed and including lower limit excluding Higher limit
randint_function

array([11,  9,  9, 23, 18, 15, 18, 10, 11, 16,  7,  6, 14, 15, 10])

In [ ]:
randint_function.reshape(5,3)

array([[11,  9,  9],
       [23, 18, 15],
       [18, 10, 11],
       [16,  7,  6],
       [14, 15, 10]])

In [ ]:
randint_function_1 = np.random.randint(6,25,(5,3))  # we can directly define the shape as 3rd parameter
randint_function_1

array([[17, 10, 14],
       [22, 24, 14],
       [18,  9,  8],
       [ 8, 16, 16],
       [13, 21, 20]])

# Indexing and Slicing

In [ ]:
p = np.random.randint(0,15,8)
p

array([ 8,  5,  5,  4,  0,  4, 11,  9])

In [ ]:
p[0] #will return value at zero index

8

In [ ]:
p[-3] # will return the value which is in third place from Last. negative indexing starts from -1,-2,-3,-4....

4

In [ ]:
p[2:8] #will return set of values start from 2 index till 8 and doesnot include 8 index value

array([ 5,  4,  0,  4, 11,  9])

In [ ]:
p[1:-4] #slicing includes negative indexing and does not include value of last index va;ue

array([5, 5, 4])

In [ ]:
p[3:] #will return the array start from 3 rd index till last and includes last index value

array([ 4,  0,  4, 11,  9])

In [ ]:
p[:-1] # will return the array start from 0 index till -1 index excluding -1 index value

array([ 8,  5,  5,  4,  0,  4, 11])

In [ ]:
p[:] # will return the array fro 0 index till last index including last index value

array([ 8,  5,  5,  4,  0,  4, 11,  9])

In [ ]:
var1 = np.random.randint(2,65,(5,5)) # return random integers betweeb 2(including) and 65(excluding) in (5,5) shape
var1

array([[64, 52, 32,  8, 44],
       [28, 25, 61, 37, 45],
       [43, 47, 62, 57,  9],
       [64, 64, 13, 20, 48],
       [49, 34,  6, 49, 39]])

In [ ]:
var1[2] #will return array at index 2

array([43, 47, 62, 57,  9])

In [ ]:
var1[2,2] #will return value at index 2 in row and 2 in column

62

In [ ]:
var1[3,[0,-1,2]] #will return array which are of 3rd indexing row  0 index value and last index value and 2 index value

array([64, 48, 13])

                Use ":" symbol for selecting range


In [ ]:
var1[3, 0:-2] #will slice the 3 rd indexed array and return array with values start from 0 index till-2 index and doesnot include -2 index value

array([64, 64, 13])

In [ ]:
var1[3, 0:3]  #will slice the 3 rd indexed array and return array with values start from 0 index till3 index and doesnot include 3 index value

array([64, 64, 13])

In [ ]:
var1[2:]      #return all the rows from 2 till last 

array([[43, 47, 62, 57,  9],
       [64, 64, 13, 20, 48],
       [49, 34,  6, 49, 39]])

In [ ]:
var1[1:,2:]     #return all the rows from 1 till last and 2 nd column till last

array([[61, 37, 45],
       [62, 57,  9],
       [13, 20, 48],
       [ 6, 49, 39]])

#conditional Indexing

In [ ]:
mn = np.random.randint(0,50,50)
mn

array([34,  9, 20,  5, 47, 27, 28,  6, 21,  2, 21,  6, 23, 47,  2, 11,  2,
        9, 34, 48,  1,  2, 15, 35,  2,  6, 30, 22, 42, 20, 34, 46, 40, 33,
       14, 17, 44, 44, 33, 24, 38,  7, 46, 15,  3, 15, 23, 15, 48, 38])

In [ ]:
mn>25 # will return bollean according to condition

array([ True, False, False, False,  True,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True,  True, False, False, False,  True, False, False,  True,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True, False,  True, False,  True, False, False,
       False, False, False,  True,  True])

In [ ]:
mn[mn>25]   #will return the values of mn which are obeying the condition

array([34, 47, 27, 28, 47, 34, 48, 35, 30, 42, 34, 46, 40, 33, 44, 44, 33,
       38, 46, 48, 38])

In [ ]:
mn[mn>30] = 25  #casting the value "25" to the values which are greater than 30
mn

array([25,  9, 20,  5, 25, 27, 28,  6, 21,  2, 21,  6, 23, 25,  2, 11,  2,
        9, 25, 25,  1,  2, 15, 25,  2,  6, 30, 22, 25, 20, 25, 25, 25, 25,
       14, 17, 25, 25, 25, 24, 25,  7, 25, 15,  3, 15, 23, 15, 25, 25])

In [ ]:
mn.resize(10,5)
mn

array([[25,  9, 20,  5, 25],
       [27, 28,  6, 21,  2],
       [21,  6, 23, 25,  2],
       [11,  2,  9, 25, 25],
       [ 1,  2, 15, 25,  2],
       [ 6, 30, 22, 25, 20],
       [25, 25, 25, 25, 14],
       [17, 25, 25, 25, 24],
       [25,  7, 25, 15,  3],
       [15, 23, 15, 25, 25]])

#creating a copy

In [ ]:
mn1 = mn[3:,2:]   #creating a copy according to indexes
mn1

array([[ 9, 25, 25],
       [15, 25,  2],
       [22, 25, 20],
       [25, 25, 14],
       [25, 25, 24],
       [25, 15,  3],
       [15, 25, 25]])

In [ ]:
mn_copy = mn.copy()   #copy() will copy the mn values and store them intomn_copy

In [ ]:
mn_copy

array([[25,  9, 20,  5, 25],
       [27, 28,  6, 21,  2],
       [21,  6, 23, 25,  2],
       [11,  2,  9, 25, 25],
       [ 1,  2, 15, 25,  2],
       [ 6, 30, 22, 25, 20],
       [25, 25, 25, 25, 14],
       [17, 25, 25, 25, 24],
       [25,  7, 25, 15,  3],
       [15, 23, 15, 25, 25]])

In [ ]:
import pandas as pd   #importing Pandas Library

In [84]:
covid_stats = pd.read_csv("/content/covid_stats.csv") #read_csv function will read the csv file in given path

In [85]:
covid_stats

State Wise Breakdown  Total Cases  Active Cases  Deaths  Cured
0                   Maharashtra        20228         15649     779   3800
1                       Gujarat         7797          5234     472   2091
2                         Delhi         6542          4454      68   2020
3                    Tamil Nadu         6535          4667      44   1824
4                     Rajasthan         3708          1440     106   2162
5                Madhya Pradesh         3457          1766     211   1480
6                 Uttar Pradesh         3373          1800      74   1499
7                Andhra Pradesh         1930           999      44    887
8                 West Bengal**         1786          1243     171    372
9                        Punjab         1762          1574      31    157
10                    Telangana         1163           382      30    751
11            Jammu and Kashmir          836           459       9    368
12                    Karnataka          794           378      30    386
13                      Haryana          675           376       9    290
14                        Bihar          611           288       5    318
15                       Kerala          505            16       4    485
16                       Odisha          294           224       2     68
17                   Chandigarh          169           143       2     24
18                    Jharkhand          156           101       3     52
19                      Tripura          135           133       0      2
20                  Uttarakhand           67            20       1     46
21                        Assam           62            26       2     34
22                 Chhattisgarh           59            16       0     43
23            Himachal Pradesh‡           53            13       3     37
24                       Ladakh           42            25       0     17
25  Andaman and Nicobar Islands           33             0       0     33
26                    Meghalaya           13             2       1     10
27                  Puducherry†           10             3       0      7
28                          Goa            7             0       0      7
29                      Manipur            2             0       0      2
30      Dadra and Nagar Haveli*            1             1       0      0
31            Arunachal Pradesh            1             0       0      1
32                      Mizoram            1             0       0      1
33                     Nagaland            1             0       0      1
34                        Total        62808         41432    2101  19275

In [86]:
covid_stats_copy = covid_stats.copy()  #copying the csv file

In [90]:
covid_stats_copy =covid_stats_copy[0:34]  #Removing the last row.. Ie, total row from the given csv
covid_stats_copy

State Wise Breakdown  Total Cases  Active Cases  Deaths  Cured
0                   Maharashtra        20228         15649     779   3800
1                       Gujarat         7797          5234     472   2091
2                         Delhi         6542          4454      68   2020
3                    Tamil Nadu         6535          4667      44   1824
4                     Rajasthan         3708          1440     106   2162
5                Madhya Pradesh         3457          1766     211   1480
6                 Uttar Pradesh         3373          1800      74   1499
7                Andhra Pradesh         1930           999      44    887
8                 West Bengal**         1786          1243     171    372
9                        Punjab         1762          1574      31    157
10                    Telangana         1163           382      30    751
11            Jammu and Kashmir          836           459       9    368
12                    Karnataka          794           378      30    386
13                      Haryana          675           376       9    290
14                        Bihar          611           288       5    318
15                       Kerala          505            16       4    485
16                       Odisha          294           224       2     68
17                   Chandigarh          169           143       2     24
18                    Jharkhand          156           101       3     52
19                      Tripura          135           133       0      2
20                  Uttarakhand           67            20       1     46
21                        Assam           62            26       2     34
22                 Chhattisgarh           59            16       0     43
23            Himachal Pradesh‡           53            13       3     37
24                       Ladakh           42            25       0     17
25  Andaman and Nicobar Islands           33             0       0     33
26                    Meghalaya           13             2       1     10
27                  Puducherry†           10             3       0      7
28                          Goa            7             0       0      7
29                      Manipur            2             0       0      2
30      Dadra and Nagar Haveli*            1             1       0      0
31            Arunachal Pradesh            1             0       0      1
32                      Mizoram            1             0       0      1
33                     Nagaland            1             0       0      1