<a href="https://colab.research.google.com/github/akhil-gali/dataScience_practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

#Create one dimensional Array in Numpy

In [ ]:
import numpy as np   #inporting numpy Library

In [ ]:
my_list = [1,2,3]
n = np.array(my_list)
n

array([1, 2, 3])

In [ ]:
type(my_list)   # type method gives the type of given variable

list

In [ ]:
type(n)    # type method gives the type of given variable

numpy.ndarray

# Creating Multidimesional Array

In [ ]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
md = np.array(my_list2)
md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(md)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(md)  # type method gives the type of given variable

numpy.ndarray

In [ ]:
md.shape # Shape method is used to return the shape of the array..

(3, 3)

#Generating Evenly Spaced values within the Given Limit

In [ ]:
np.arange(0,10)  # gives array of numbers start from "0" till "9" excluding the last digit

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(20)  #if start number doesn't mention, Np will generate starting from 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20,3) #will generate numbers from "0" to "20" with interval of "3"

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
for i in range(1,11,2):
  print(i)                    #printing the Number

1
3
5
7
9


In [ ]:
for i in np.arange(1,12,2):
  print(np.arange(i,12,2))            #Printing the Array

[ 1  3  5  7  9 11]
[ 3  5  7  9 11]
[ 5  7  9 11]
[ 7  9 11]
[ 9 11]
[11]
